PHI_TRANSFORMERS_CONFIG = {
    "PRESIDIO_SUPPORTED_ENTITIES": [
        "PATIENT",
        "PRACTITIONER",
        "AGE",
        "DATE_TIME",
        "PHONE_NUMBER",
        "ID",
        "EMAIL",
        "ORGANIZATION",
        "PROVIDER",
        "LOCATION",
    ],
    "DEFAULT_MODEL_PATH": "obi/deid_roberta_i2b2",
    "LABELS_TO_IGNORE": ["O"],
    "DEFAULT_EXPLANATION": "Identified as {} by the obi/deid_roberta_i2b2 NER model",
    "SUB_WORD_AGGREGATION": "simple",
    "DATASET_TO_PRESIDIO_MAPPING": {
        "PATIENT": "PATIENT",
        "STAFF": "PRACTITIONER",
        "AGE": "AGE",
        "DATE": "DATE_TIME",
        "PHONE": "PHONE_NUMBER",
        "ID": "ID",
        "EMAIL": "EMAIL",
        "PATORG": "ORGANIZATION",
        "LOC": "LOCATION",
        "HOSP": "PROVIDER",
    },
    "MODEL_TO_PRESIDIO_MAPPING": {
        "PATIENT": "PATIENT",
        "STAFF": "PRACTITIONER",
        "AGE": "AGE",
        "DATE": "DATE_TIME",
        "PHONE": "PHONE_NUMBER",
        "ID": "ID",
        "EMAIL": "EMAIL",
        "PATORG": "ORGANIZATION",
        "LOC": "LOCATION",
        "HOSP": "PROVIDER",
    },
    "CHUNK_OVERLAP_SIZE": 40,
    "CHUNK_SIZE": 600,
    "ID_SCORE_MULTIPLIER": 0.4,
    "ID_ENTITY_NAME": "ID"
}